@echo off
REM Starts a single-node Apache Kafka 4.x broker in KRaft mode (no ZooKeeper) for local development.
REM   KAFKA_HOME  - Kafka installation (default C:\Softwares\kafka\kafka_2.13-4.3.1)
REM   KAFKA_DATA  - log directory       (default %KAFKA_HOME%\data, created and formatted on first run)
REM Listens on localhost:9092. Stop with Ctrl+C (or scripts\kafka-stop.cmd).
setlocal
if "%KAFKA_HOME%"=="" set KAFKA_HOME=C:\Softwares\kafka\kafka_2.13-4.3.1
if "%KAFKA_DATA%"=="" set KAFKA_DATA=%KAFKA_HOME%\data
if not exist "%KAFKA_HOME%\bin\windows\kafka-server-start.bat" (
  echo Kafka not found under %KAFKA_HOME%. Download kafka_2.13-4.3.1.tgz from https://kafka.apache.org/downloads and extract it there.
  exit /b 1
)
set KAFKA_CONFIG=%KAFKA_HOME%\config\local-kraft.properties
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0kafka-patch-classpath.ps1" -KafkaHome "%KAFKA_HOME%"
set KAFKA_DATA_FWD=%KAFKA_DATA:\=/%
if exist "%KAFKA_CONFIG%" goto :format
echo Writing %KAFKA_CONFIG%
>"%KAFKA_CONFIG%" echo # Generated by scripts\kafka-start.cmd - single node, combined broker+controller, KRaft mode
>>"%KAFKA_CONFIG%" echo process.roles=broker,controller
>>"%KAFKA_CONFIG%" echo node.id=1
>>"%KAFKA_CONFIG%" echo controller.quorum.voters=1@localhost:9093
>>"%KAFKA_CONFIG%" echo listeners=PLAINTEXT://:9092,CONTROLLER://:9093
>>"%KAFKA_CONFIG%" echo advertised.listeners=PLAINTEXT://localhost:9092
>>"%KAFKA_CONFIG%" echo controller.listener.names=CONTROLLER
>>"%KAFKA_CONFIG%" echo inter.broker.listener.name=PLAINTEXT
>>"%KAFKA_CONFIG%" echo listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
>>"%KAFKA_CONFIG%" echo log.dirs=%KAFKA_DATA_FWD%
>>"%KAFKA_CONFIG%" echo num.partitions=3
>>"%KAFKA_CONFIG%" echo offsets.topic.replication.factor=1
>>"%KAFKA_CONFIG%" echo transaction.state.log.replication.factor=1
>>"%KAFKA_CONFIG%" echo transaction.state.log.min.isr=1
>>"%KAFKA_CONFIG%" echo share.coordinator.state.topic.replication.factor=1
>>"%KAFKA_CONFIG%" echo share.coordinator.state.topic.min.isr=1
>>"%KAFKA_CONFIG%" echo auto.create.topics.enable=true
>>"%KAFKA_CONFIG%" echo # Windows cannot delete memory-mapped segment files while the broker runs: keep retention long so the
>>"%KAFKA_CONFIG%" echo # log cleaner never tries during a dev session, otherwise the broker crashes on the failed delete.
>>"%KAFKA_CONFIG%" echo log.retention.hours=168
>>"%KAFKA_CONFIG%" echo log.segment.bytes=1073741824
:format
if exist "%KAFKA_DATA%\meta.properties" goto :start
echo Formatting KRaft storage in %KAFKA_DATA%
for /f "usebackq delims=" %%i in (`call "%KAFKA_HOME%\bin\windows\kafka-storage.bat" random-uuid`) do set CLUSTER_ID=%%i
echo Cluster id %CLUSTER_ID%
call "%KAFKA_HOME%\bin\windows\kafka-storage.bat" format -t %CLUSTER_ID% -c "%KAFKA_CONFIG%"
if errorlevel 1 exit /b 1
:start
rem Fixed heap: also skips kafka-server-start.bat's wmic architecture probe (wmic no longer ships with Windows 11)
if "%KAFKA_HEAP_OPTS%"=="" set KAFKA_HEAP_OPTS=-Xms512M -Xmx1G
echo Starting Kafka - KRaft - on localhost:9092, data in %KAFKA_DATA%
call "%KAFKA_HOME%\bin\windows\kafka-server-start.bat" "%KAFKA_CONFIG%"
